import * as pdfjsLib from "https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs";
pdfjsLib.GlobalWorkerOptions.workerSrc="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs";
const $=id=>document.getElementById(id);const pdfInput=$("pdfInput"),uploadBtn=$("uploadBtn"),welcomeUpload=$("welcomeUpload"),welcome=$("welcome"),editor=$("editor"),pdfContainer=$("pdfContainer"),pdfArea=$("pdfArea");
const prevPage=$("prevPage"),nextPage=$("nextPage"),pageInfo=$("pageInfo"),zoomOut=$("zoomOut"),zoomIn=$("zoomIn"),fitPage=$("fitPage"),zoomInfo=$("zoomInfo"),addText=$("addText"),addName=$("addName"),addDate=$("addDate"),addSignature=$("addSignature"),undoBtn=$("undo"),deleteSelected=$("deleteSelected"),exportPdf=$("exportPdf");
const textDialog=$("textDialog"),textInput=$("textInput"),textDialogTitle=$("textDialogTitle"),textCancel=$("textCancel"),textConfirm=$("textConfirm");const signatureDialog=$("signatureDialog"),signatureCanvas=$("signatureCanvas"),signatureClear=$("signatureClear"),signatureCancel=$("signatureCancel"),signatureConfirm=$("signatureConfirm");
let pdfDocument=null,currentPage=1,zoom=1,renderVersion=0,sourcePdfBytes=null,sourceFileName="document",selectedId=null,pendingTextType="text",history=[];let annotations=new Map();
const SUPPORTED=new Set(["pdf","jpg","jpeg","png","webp","heic","heif"]);
const ext=n=>{const p=n.toLowerCase().split(".");return p.length>1?p.pop():""};const supported=f=>SUPPORTED.has(ext(f.name));
function snapshot(){return JSON.stringify([...annotations.entries()])}function restore(s){annotations=new Map(JSON.parse(s));selectedId=null}function commit(){history.push(snapshot());if(history.length>50)history.shift();}
function currentList(){return annotations.get(currentPage)||[]}function setCurrentList(list){annotations.set(currentPage,list)}
function newId(){return crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`}
function openPicker(){pdfInput.value="";pdfInput.click()}uploadBtn.onclick=openPicker;welcomeUpload.onclick=openPicker;
pdfInput.onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{await openDocument(f)}catch(err){console.error(err);alert("This file could not be opened. Please check that it is a valid PDF or supported image.")}};
async function openDocument(file){if(!supported(file))throw Error("Unsupported format");let bytes=ext(file.name)==="pdf"?new Uint8Array(await file.arrayBuffer()):await imageFileToPdf(file);const task=pdfjsLib.getDocument({data:bytes});const doc=await task.promise;sourcePdfBytes=bytes;sourceFileName=file.name.replace(/\.[^.]+$/i,"")||"document";pdfDocument=doc;currentPage=1;zoom=1;annotations=new Map();history=[];selectedId=null;welcome.classList.add("hidden");editor.classList.remove("hidden");await renderPage()}
async function imageFileToPdf(file){const L=window.PDFLib;if(!L?.PDFDocument)throw Error("pdf-lib unavailable");let blob=file;const e=ext(file.name);if(e==="heic"||e==="heif"){if(typeof window.heic2any!=="function")throw Error("HEIC decoder unavailable");blob=await window.heic2any({blob:file,toType:"image/png"});if(Array.isArray(blob))blob=blob[0]}const url=URL.createObjectURL(blob);try{const img=await loadImage(url),w=img.naturalWidth||img.width,h=img.naturalHeight||img.height;if(!w||!h)throw Error("Invalid image");const max=3000,s=Math.min(1,max/Math.max(w,h)),c=document.createElement("canvas");c.width=Math.max(1,Math.round(w*s));c.height=Math.max(1,Math.round(h*s));const ctx=c.getContext("2d",{alpha:false});ctx.fillStyle="#fff";ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(img,0,0,c.width,c.height);const b=await new Promise((res,rej)=>c.toBlob(x=>x?res(x):rej(Error("PNG conversion failed")),"image/png"));const p=await L.PDFDocument.create(),im=await p.embedPng(new Uint8Array(await b.arrayBuffer())),page=p.addPage([w,h]);page.drawImage(im,{x:0,y:0,width:w,height:h});return new Uint8Array(await p.save())}finally{URL.revokeObjectURL(url)}}
function loadImage(url){return new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=()=>rej(Error("Image decode failed"));i.src=url})}
function today(){const d=new Date();return `${String(d.getDate()).padStart(2,"0")}/${String(d.getMonth()+1).padStart(2,"0")}/${d.getFullYear()}`}
function addTextLike(type,value){commit();const list=currentList();list.push({id:newId(),type,text:value,x:35,y:35,w:type==="signature"?180:150,h:type==="signature"?70:34,fontSize:type==="date"?18:18});setCurrentList(list);selectedId=list.at(-1).id;renderPage()}
function showTextDialog(type){pendingTextType=type;textDialogTitle.textContent=type==="name"?"Add name":"Add text";textInput.value="";textDialog.classList.remove("hidden");setTimeout(()=>textInput.focus(),50)}
addText.onclick=()=>showTextDialog("text");addName.onclick=()=>showTextDialog("name");addDate.onclick=()=>{commit();const l=currentList();l.push({id:newId(),type:"date",text:today(),x:35,y:35,w:130,h:34,fontSize:18});setCurrentList(l);selectedId=l.at(-1).id;renderPage()};
textCancel.onclick=()=>textDialog.classList.add("hidden");textConfirm.onclick=()=>{const v=textInput.value.trim();if(v){addTextLike(pendingTextType,v);textDialog.classList.add("hidden")}};textInput.onkeydown=e=>{if(e.key==="Enter")textConfirm.click();if(e.key==="Escape")textCancel.click()};
let drawing=false,signatureHasInk=false,sigCtx=signatureCanvas.getContext("2d");function resizeSig(){const r=signatureCanvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);signatureCanvas.width=Math.max(1,Math.round(r.width*d));signatureCanvas.height=Math.max(1,Math.round(r.height*d));sigCtx.setTransform(d,0,0,d,0,0);sigCtx.lineWidth=2.4;sigCtx.lineCap="round";sigCtx.lineJoin="round";sigCtx.strokeStyle="#111827"}function sigPoint(e){const r=signatureCanvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}function beginSig(e){drawing=true;signatureHasInk=true;const p=sigPoint(e);sigCtx.beginPath();sigCtx.moveTo(p.x,p.y);signatureCanvas.setPointerCapture?.(e.pointerId);e.preventDefault()}function moveSig(e){if(!drawing)return;const p=sigPoint(e);sigCtx.lineTo(p.x,p.y);sigCtx.stroke();e.preventDefault()}function endSig(){drawing=false}signatureCanvas.addEventListener("pointerdown",beginSig);signatureCanvas.addEventListener("pointermove",moveSig);signatureCanvas.addEventListener("pointerup",endSig);signatureCanvas.addEventListener("pointercancel",endSig);
function clearSig(){resizeSig();signatureHasInk=false}addSignature.onclick=()=>{signatureDialog.classList.remove("hidden");setTimeout(clearSig,20)};signatureClear.onclick=clearSig;signatureCancel.onclick=()=>signatureDialog.classList.add("hidden");signatureConfirm.onclick=()=>{if(!signatureHasInk){alert("Please draw a signature first.");return}const data=signatureCanvas.toDataURL("image/png");commit();const l=currentList();l.push({id:newId(),type:"signature",data,x:35,y:35,w:180,h:70,fontSize:0});setCurrentList(l);selectedId=l.at(-1).id;signatureDialog.classList.add("hidden");renderPage()};
function select(id){selectedId=id;document.querySelectorAll(".annotation").forEach(e=>e.classList.toggle("selected",e.dataset.id===id));updateControls()}
function removeSelected(){if(!selectedId)return;const l=currentList(),i=l.findIndex(a=>a.id===selectedId);if(i<0)return;commit();l.splice(i,1);setCurrentList(l);selectedId=null;renderPage()}
deleteSelected.onclick=removeSelected;
function makeAnnotation(a,wrapper){const el=document.createElement("div");el.className=`annotation ${a.type}${a.id===selectedId?" selected":""}`;el.dataset.id=a.id;el.style.left=`${a.x*zoom}px`;el.style.top=`${a.y*zoom}px`;el.style.width=`${a.w*zoom}px`;el.style.height=`${a.h*zoom}px`;if(a.type!=="signature"){el.textContent=a.text;el.style.fontSize=`${a.fontSize*zoom}px`;el.style.display="flex";el.style.alignItems="center"}else{const img=document.createElement("img");img.src=a.data;el.appendChild(img)}const del=document.createElement("button");del.className="delete-handle";del.textContent="×";del.title="Delete";del.onclick=e=>{e.stopPropagation();select(a.id);removeSelected()};const handle=document.createElement("span");handle.className="resize-handle";el.append(del,handle);
let mode=null,sx=0,sy=0,ax=0,ay=0,aw=0,ah=0;el.addEventListener("pointerdown",e=>{if(e.target===del||e.target===handle)return;select(a.id);mode="move";sx=e.clientX;sy=e.clientY;ax=a.x;ay=a.y;try{el.setPointerCapture(e.pointerId)}catch{}e.preventDefault();e.stopPropagation()});handle.addEventListener("pointerdown",e=>{select(a.id);mode="resize";sx=e.clientX;sy=e.clientY;aw=a.w;ah=a.h;try{handle.setPointerCapture(e.pointerId)}catch{}e.preventDefault();e.stopPropagation()});el.addEventListener("pointermove",e=>{if(!mode)return;if(mode==="move"){a.x=Math.max(0,ax+(e.clientX-sx)/zoom);a.y=Math.max(0,ay+(e.clientY-sy)/zoom)}else{a.w=Math.max(45,aw+(e.clientX-sx)/zoom);a.h=Math.max(24,ah+(e.clientY-sy)/zoom)}el.style.left=`${a.x*zoom}px`;el.style.top=`${a.y*zoom}px`;el.style.width=`${a.w*zoom}px`;el.style.height=`${a.h*zoom}px`;if(a.type!=="signature")el.style.fontSize=`${a.fontSize*zoom}px`});const stop=()=>{if(mode){commit();mode=null}};el.addEventListener("pointerup",stop);el.addEventListener("pointercancel",stop);wrapper.appendChild(el)}
async function renderPage(){if(!pdfDocument)return;const ver=++renderVersion,pn=currentPage,page=await pdfDocument.getPage(pn),vp=page.getViewport({scale:zoom}),canvas=document.createElement("canvas"),ctx=canvas.getContext("2d",{alpha:false}),ds=Math.min(devicePixelRatio||1,2);canvas.className="pdf-page";canvas.width=Math.floor(vp.width*ds);canvas.height=Math.floor(vp.height*ds);canvas.style.width=`${vp.width}px`;canvas.style.height=`${vp.height}px`;await page.render({canvasContext:ctx,viewport:vp,transform:ds!==1?[ds,0,0,ds,0,0]:undefined}).promise;if(ver!==renderVersion||pn!==currentPage)return;const wrap=document.createElement("div");wrap.className="pdf-page-wrapper";wrap.style.width=`${vp.width}px`;wrap.style.height=`${vp.height}px`;wrap.appendChild(canvas);for(const a of currentList())makeAnnotation(a,wrap);pdfContainer.replaceChildren(wrap);updateControls()}
function updateControls(){pageInfo.textContent=`Page ${currentPage} / ${pdfDocument?.numPages||1}`;zoomInfo.textContent=`${Math.round(zoom*100)}%`;prevPage.disabled=!pdfDocument||currentPage<=1;nextPage.disabled=!pdfDocument||currentPage>=pdfDocument.numPages;undoBtn.disabled=!history.length;deleteSelected.disabled=!selectedId}
prevPage.onclick=async()=>{if(currentPage>1){currentPage--;selectedId=null;await renderPage()}};nextPage.onclick=async()=>{if(pdfDocument&&currentPage<pdfDocument.numPages){currentPage++;selectedId=null;await renderPage()}};zoomOut.onclick=async()=>{if(pdfDocument){zoom=Math.max(.35,Math.round((zoom-.1)*10)/10);await renderPage()}};zoomIn.onclick=async()=>{if(pdfDocument){zoom=Math.min(3,Math.round((zoom+.1)*10)/10);await renderPage()}};fitPage.onclick=async()=>{if(!pdfDocument)return;const p=await pdfDocument.getPage(currentPage),u=p.getViewport({scale:1}),available=Math.max(180,pdfArea.clientWidth-24),target=Math.min(available/u.width,2.5);zoom=Math.max(.25,Math.round(target*100)/100);await renderPage()};undoBtn.onclick=async()=>{if(!history.length)return;restore(history.pop());await renderPage()};
async function exportDocument(){if(!sourcePdfBytes)return;const L=window.PDFLib;if(!L?.PDFDocument){alert("PDF export library is unavailable.");return}exportPdf.disabled=true;exportPdf.textContent="Exporting…";try{const out=await L.PDFDocument.load(sourcePdfBytes),font=await out.embedFont(L.StandardFonts.Helvetica),pages=out.getPages();for(let i=0;i<pages.length;i++){const page=pages[i],pw=page.getWidth(),ph=page.getHeight();for(const a of annotations.get(i+1)||[]){const x=Math.max(0,Math.min(a.x,pw-a.w)),top=Math.max(0,Math.min(a.y,ph-a.h)),y=ph-top-a.h;if(a.type==="signature"){const img=await out.embedPng(dataUrlBytes(a.data));page.drawImage(img,{x,y,width:a.w,height:a.h})}else{const fs=Math.max(6,Math.min(96,a.fontSize));page.drawText(a.text,{x:x+5,y:y+(a.h-fs)/2,size:fs,font,color:L.rgb(.067,.094,.153),maxWidth:Math.max(10,a.w-10),lineHeight:fs})}}}const bytes=await out.save(),blob=new Blob([bytes],{type:"application/pdf"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`${sourceFileName}-signed.pdf`;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}catch(e){console.error(e);alert("The PDF could not be exported. Please try again.")}finally{exportPdf.disabled=false;exportPdf.textContent="Export PDF"}}exportPdf.onclick=exportDocument;
function dataUrlBytes(data){const b=atob(data.split(",")[1]);const a=new Uint8Array(b.length);for(let i=0;i<b.length;i++)a[i]=b.charCodeAt(i);return a}
window.addEventListener("resize",()=>{if(signatureDialog&&!signatureDialog.classList.contains("hidden"))resizeSig()});
updateControls();
